### ISSUE TITLE
用户注册

### ISSUE THREAD

**Issue by 88250** [b3log/symphony-weapp#2]

**Comment by andyComeOn** [comment]
V：最近研究小程序，发现以下问题，想给你交流一下，就是登录问题，在官方文档上有`wx.login()`板块。

1，我理解是只要是在登录的逻辑块，写上wx.login(***),在客服端就会有这个弹窗提示？如下截图所示(http://www.chinaconnect.site/img/login.jpg)，点击允许之后才会按照`wx.login()`中往下走，才会给res.code?在开发工具中是直接可以打印出来这个res.code，说明代码已经到走了这一步。由于小程序没有上线是不是这个弹窗提示就不能在手机上模拟出来。

2，新建项目时候小程序帮助你完成了初始化，其中在app.js中有初始化的一些代码。代码是获取了全局的用户信息。如果在其他页面中如果用到了用户 的信息，就会在对应的页面js中加入 ```
;首先加上这个全局引入
var app = getApp()
在下面调用。
onLoad: function (option) {
    var that = this;
    app.getUserInfo(function (userInfo) {
      that.setData({
        userInfo: userInfo
      })
    });
}
```
在这个引入的函数没有搞明白```
function (userInfo) {
      that.setData({
        userInfo: userInfo
      })
    }
```
这个userInfo是参数传到app.js中，可是在app.js中，有这个代码```
getUserInfo: function (cb) {
		var that = this;
		if (this.globalData.userInfo) {
			typeof cb == "function" && cb(this.globalData.userInfo)
		} else {
			//调用登录接口
			wx.login({
				success: function (res) {
					wx.getUserInfo({
						success: function (res) {
							that.globalData.userInfo = res.userInfo
							typeof cb == "function" && cb(that.globalData.userInfo)
						}
					})

					
				}
			})
		}
	},

```
传得是什么？怎么获取的，一直没有走明白。
3，想在app.js中 用已知的从微信给的用户信息到自己的后台获取uid,因为每个页面都需要用到uid.所以想在app.js中完成这个请求， 获得uid,以便其他页面使用。由于没有搞明白这个app.js初始化的一些代码，一直止步不前。

**Comment by Vanessa219** [comment]
1. 不上线也可以的
2. 按照你的写法 userInfo 是设置到当前的 js 文件中
3. 

    // app.js
    App({
      uid: ''
    })
    // getUserInfo.js
    var app = getApp();
    app.uid = 'uid'

后面按照 `getApp().uid` 就可以获取 uid 了
